### ISSUE TITLE
LinearAlgebra.mul!에서

### ISSUE THREAD

**Issue by Seungbongjung** [kose-y/DistStat.jl#13]
LinearAlgebra.mul!(C::AbstractVector{T}, A::Transpose{T, MPIMatrix{T,AT}}, B::AbstractVector{T}) where {T,AT} 

이 함수에 대한 testcode만 짜면 우선 이번주까지 짜여하는 code들은 다 짜게 되는데 저 함수의 경우 output의 모든 element가 0이 나오는 게 맞나요? 대충 distlinalg.jl 에서 source code읽어 보았는데 이해한게 맞는지 여쭙고자 issue로 남깁니다.

**Comment by Seungbongjung** [comment]
우선 실행해봤을 때에는 그렇게 결과가 나왔습니다.

**Comment by kose-y** [comment]
C가 행렬 A와 벡터 B의 곱인 것이 아니면 버그입니다.

**Comment by kose-y** [comment]
```julia
function LinearAlgebra.mul!(C::AbstractVector{T}, A::Transpose{T, MPIMatrix{T,AT}}, B::AbstractVector{T}) where {T,AT}
    localA = get_local(A)
    fill!(C, zero(T))
    LinearAlgebra.mul!(C[transpose(A).partitioning[Rank()+1][2]], localA, B[transpose(A).partitioning[Rank()+1][1]])
    sync()
    Allreduce!(C)
    C
end
```
코드의 의도는 
모든 프로세스에서 C에 일단 0을 넣고 C의 한 부분에 A의 local 부분과 B를 곱한 뒤 `Allreduce!`를 통해 이를 모두 더해 모든 process에 A * B가 들어오게 하는 것입니다.

**Comment by Seungbongjung** [comment]
네 그럼 우선 이외의 코드들은 commit하겠습니다. 감사합니다.
