### ISSUE TITLE
`fill_diag!`

### ISSUE THREAD

**Issue by Seungbongjung** [kose-y/DistStat.jl#3]
cannot find `fill_diag!` outside testing

**Comment by kose-y** [comment]
문제가 생겼던 원인은 홈 디렉토리에 DistStat.jl의 클론이 또 있어서였던 것으로 확인했습니다. apeach의 계정에 해당 클론을 삭제하고 julia environment를 리셋한 뒤 DistStat.jl 패키지를 다시 dev mode로 설치했습니다 (branch도 unittest로 두었습니다). 이외의 다른 패키지들은 새로 설치해서 사용하면 됩니다.
